### ISSUE TITLE
no authentication, no error

### ISSUE THREAD

**Issue by lesfleurs** [Happyr/LinkedIn-API-client#22] opened 2014-12-24 23:06 UTC
My app redirects successfully to the authorization dialog but never gets an access code. I receive the state and an authorization code but cant seem to retrieve a token for the user and the api is showing no error. i suspect it is a session issue but i am not sure.

**Comment by Nyholm** [comment] 2015-01-02 07:29
Duplicate of #20

**Closed by Nyholm** 2015-01-02 07:29 UTC
